name: VanishPlugin
version: '${project.version}'
main: me.pox.vanishplugin.VanishPlugin
api-version: '1.20'
authors: [ PoXel6 ]
commands:
  vanish:
    description: hide player from other players
    usage: /<command>
    aliases: v